const data = {
  products: [
    {
      _Id: '1',
      name: 'wallpanels',
      slug: 'wallpanels',
      category: 'interior products',
      image: '/image/wallpanel1.0.jpeg',
      price: '40',
      countInStock: '0',
      brand: 'fibre',
      rating: '4.5',
      numReviews: '10',
      discription: 'high quality interior product',
    },
    {
      _Id: '2',
      name: 'fluted-panel',
      slug: 'fluted-panel',
      category: 'interior products',
      image: '/image/fluted1.0.jpeg',
      price: '40',
      countInStock: '200',
      brand: 'fibre',
      rating: '4.5',
      numReviews: '10',
      discription: 'high quality interior product',
    },
    {
      _Id: '3',
      name: 'silkplaster',
      slug: 'silk-plaster',
      category: 'interior products',
      image: '/image/silk1.0.jpeg',
      price: '40',
      countInStock: '200',
      brand: 'cotton fibre',
      rating: '4.5',
      numReviews: '10',
      discription: 'high quality interior product',
    },
    {
      _Id: '4',
      name: 'wallpaper',
      slug: 'wallpaper',
      category: 'interior products',
      image: '/image/wallpaper2.0.jpg',
      price: '40',
      countInStock: '400',
      brand: 'paper',
      rating: '4.5',
      numReviews: '10',
      discription: 'high quality interior product',
    },
  ],
};
export default data;
